#lang ivy1.7

type id_t
type set_t
type val_t

interpret id_t -> bv[1]
interpret set_t -> bv[2]
interpret val_t -> bv[1]

# For some reason the following properties aren't implied by the 'interpret'
# declarations, though it seems like they should be.

property [exactly_two_nodes] forall N:id_t. N = 0 | N = 1
property [exactly_two_values] forall V:val_t. V = 0 | V = 1
property [exactly_four_sets] forall S:set_t. S = 0 | S = 1 | S = 2 | S = 3
