#lang ivy1.7

include set

type id_t
type val_t
instance nset : set(id_t)

include node
include network

# Allow IVy to cause any number of vote_for actions to initiate activities on
# individual nodes.
export node(ID).vote_for

# Allow Ivy to initiate messages from the network side
export network.broadcast_vote
export network.deliver_vote
export network.broadcast_accept
export network.deliver_accept
